{% set name = "napari_video" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_video-{{ version }}.tar.gz
  sha256: 0a81ea583d8562d5ed2226b323a77f7953a98aa1b2276213788352c18c16b29c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - pyvideoreader
    - napari-plugin-engine >=0.1.4
    # adding dask-core due to unused import; remove in next release!
    - dask-core

test:
  imports:
    - napari_video.napari_video
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/janclemenslab/napari-video
  summary: napari plugin for reading videos.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - postpop
